
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1200
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200
#define CHARYBDIS_MINIMUM_SNIPING_DPI 400
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 200
#define CHARYBDIS_DRAGSCROLL_DPI 100
#define CHARYBDIS_DRAGSCROLL_REVERSE_X / _Y
#define CHARYBDIS_CARRET_BUFFER 40
#define CHARYBDIS_CARRET_REVERSE_X / _Y
// #define CHARYBDIS_POINTER_ACCELERATION_ENABLE
// #define CHARYBDIS_POINTER_ACCELERATION_FACTOR 24

// 200 is the default, increase this if we want mouse layer on cursor move to last longer
// #define AUTO_MOUSE_DELAY 200

#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_USB_TIMEOUT 2000

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
// only required if not setting mouse layer elsewhere
#define AUTO_MOUSE_DEFAULT_LAYER 3
#define AUTO_MOUSE_TIME 850//Default is 650ms

// #define CUSTOM_FN_RIGHT / CUSTOM_FN_LEFT / _UP / _DOWN